### ISSUE TITLE
publish a 1.0.0 version

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/lints#16]
We should publish a 1.0.0 version of this package; that's likely a blocker for contributing this to `dart create` (unless we want to consume a dev version of this package).

Publishing 1.0.0 is likely blocked by #15 and #5?

**Comment by pq** [comment]
cc @mit-mit for thoughts.

**Comment by goderbauer** [comment]
Publishing the migration guide in https://github.com/flutter/website/pull/5749 is also blocked on having a non-pre-release version of `package:flutter_lints`, which depends on having a non-pre-release version of `package:lints`.

Otherwise, `flutter pub add --dev flutter_lints` from the guide doesn't do the right thing.

**Comment by mit-mit** [comment]
I agree we should block on the readme; made a PR for that in https://github.com/dart-lang/lints/pull/18

I don't think we have to block on https://github.com/dart-lang/lints/issues/5. For now I linked (in the readme PR) to https://dart.dev/tools/linter-rules

**Comment by mit-mit** [comment]
I suggest we publish after merging https://github.com/dart-lang/lints/pull/22 and https://github.com/dart-lang/lints/pull/21

**Comment by mit-mit** [comment]
1.0 was published
