### ISSUE TITLE
Remove `package_prefixed_library_names` from core set (and deprecate)

### ISSUE THREAD

**Issue by parlough** [dart-lang/lints#172]
I'm opening this issue in this repository to discuss how to handle ecosystem affecting linter rule changes, such as this case when one of the effected lints is in one of the core sets. _(As requested by Brian)_

Currently, [`package_prefixed_library_names`](https://dart.dev/lints/package_prefixed_library_names) which is in the core set isn't functional. The same goes for [`package_api_docs`](https://dart.dev/lints/package_api_docs) which isn't in any of the core sets currently. This has been the case for the past few releases after https://github.com/dart-lang/linter/commit/008a8a0a0196a1cde0ff2891af3db09fe839937e.

Fixing/reimplementing these lints now is a bit dangerous as they are both quite heavily depended on, especially with `package_prefixed_library_names` as part of the core set. It could result in a lot of new lints triggering on code with an SDK update.

So the question is if those lints starting to trigger on an SDK update are ok, or should these lints be removed from the core sets, deprecated, and slated for removal? If their functionality is still desired, we can always introduce new lints. Technically these both don't follow today's linter rule naming scheme anyway.

As an aside for these two rules specifically, but not relevant to the question of how to handle this in general:

- I think `package_prefixed_library_names` isn't super useful since users should generally shouldn't name libraries anymore.
- While not the exact same behavior, [`public_member_api_docs`](https://dart.dev/lints/public_member_api_docs) covers many of the use cases of `package_api_docs`.

\cc @bwilkerson @pq @devoncarew

**Comment by devoncarew** [comment]
@natebosch @goderbauer @lrhn - can you review this proposal and give an initial thumbs-up / thumbs-down (with some rational if useful)?

**Comment by natebosch** [comment]
Is there risk of users not getting help if they add a library name unnecessarily, and the library name doesn't follow these patterns? Should we be linting to encourage unnamed libraries?

If the lint is currently not firing, I'm on board with removing it from the lint sets before (or instead of) fixing the lint implementation. I do think it's lower value now that we can have bare `library;` and I'd be OK with not having any lints at all around library names if we think that's easier for us.

**Comment by goderbauer** [comment]
Maybe we should consider [`unnecessary_library_directive`](https://dart.dev/tools/linter-rules/package_prefixed_library_names) for inclusion in recommended to cut down on library statements? 

Since the lint is not working (@parlough is there a bug on file for this?) I'd be ok with removing it.

**Comment by natebosch** [comment]
`unnecessary_library_directive` SGTM. I'd lean towards core, but I'd be fine with recommended.

**Comment by parlough** [comment]
> Since the lint is not working (@parlough is there a bug on file for this?) I'd be ok with removing it.

https://github.com/dart-lang/linter/issues/3395 is the original bug.

> Maybe we should consider [unnecessary_library_directive](https://dart.dev/tools/linter-rules/package_prefixed_library_names) for inclusion in recommended to cut down on library statements?

+1 Yes please.

**Comment by parlough** [comment]
It sounds like there's agreement that it's okay to remove this lint because it doesn't work, but there's also some thoughts that the lint isn't super valuable anymore.

I'd propose the following:

1. Remove `package_prefixed_library_names` from `package:lints`
2. Add `unnecessary_library_directive` to the core lints
3. Deprecate `package_prefixed_library_names`
4.  Implement [`unnecessary_library_names`](https://github.com/dart-lang/linter/issues/3882) which should supersede it.
5. Add `unnecessary_library_name` to the core lints

**Comment by lrhn** [comment]
If you do give your library a name (why?) then I think it is a good idea to include your package name in the library name. 

I just wrote `library pkg.packageName.impl;`, and I prefer that to just prefixing with the package name alone, because I don't necessarily expect pub packages to be the only kind of code.
(I needed the library name for a hack including parts and conditional imports, which could be better handled by conditional augments).

Ok with removing the lint.
Ok with `unnecessary_library_name`.
Ok with removing library names from the language (when we get conditional augments).

**Comment by devoncarew** [comment]
After discussion, we're in favor of removing this lint from the core set. The other items discussed in this issue (`unnecessary_library_directive`, creating a `unnecessary_library_name` lint, ...) will be followed up on elsewhere.
