### ISSUE TITLE
Add `unnecessary_library_directive`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/lints#178]
> Avoid library directives unless they have documentation comments or annotations.

Creating this issue as a companion to https://github.com/dart-lang/lints/issues/172 (see comments https://github.com/dart-lang/lints/issues/172#issuecomment-1931025743, https://github.com/dart-lang/lints/issues/172#issuecomment-1931045670).

This lint - along with a few others - would help with general library statement hygiene.

**Comment by devoncarew** [comment]
@natebosch @goderbauer @lrhn - can you weigh in here (even if you have already on #172)?

cc @parlough

**Comment by goderbauer** [comment]
I am in favor of adding this lint. My suggestion would be to add it to recommended since IMO it does not "help identify critical issues that are likely to lead to problems when running or consuming Dart code", which has been our bar for core lints.

**Comment by lrhn** [comment]
Link: https://dart.dev/tools/linter-rules/unnecessary_library_directive

It's not that bad. It's not great. 
I really can't bring myself to care whether people write `library;` at the top of their library.

I'm fine with putting it in google internal lints, or Dart/Flutter team lints, where people care a lot about conformance to a single style.
Optional lint for people who want it, sure. Recommended or core, not worth it.

But I don't want to bother our users with this, because it *really* doesn't matter.
It's not about telling people that you *can* remove this library declaration. Giving a warning is telling them that they *should*. And they really don't need to, by any reasonable measure.

Recommended lints should have significant *value*. We are bothering our users about something, so that better be *meaningful*. It better make their code *better* in at least some way.

This is just noise. Nobody's day gets better because we make them remove `library;`.

**Comment by natebosch** [comment]
I think removing noise is enough justification for recommended. I'm sold on keeping it out of core.

This is another one which might be best as a transient lint. In the absence of that capability I think users of the recommended set would benefit enough to make it worth including.

I still see packages come in to google3 with unnecessary library names that look to me like a habit of copy/paste. If we recommend a lint that requires `library;` without names I think this one goes along well with it.

**Comment by lrhn** [comment]
> removing noise 

To be precise, I was considering the *lint* to be the noise, not the `library;` declaration.

Warnings about things that don't actually matter is worse than having things that don't actually matter.  
I know it's a fine line to draw between "unnecessary code" and this, but the reason we generally discourage unnecessary code isn't that it's inherently bad, but that it's potentially *confusing*. A reader may see something which is more complicated than necessary, and start looking for a reason where there is none. That's a cost on the reader.

I expect the cost on someone seeing a `library;` with no comment or annotation to be exactly zero. There is nothing to be confused about.
Showing a warning that you should remove the `library;` *is* a cost, no matter how small, and with a straight zero benfit I don't think it's worth it.

There is just no value at a normal user, or future readers of their same code, from telling them to remove a `library;` declaration. 
If it doesn't bother them, that's all that matters. If it does, I think they'll know to remove it.
