### ISSUE TITLE
proposal: have a ruleset which enables all rules by default

### ISSUE THREAD

**Issue by DetachHead** [dart-lang/lints#74]
**Describe the rule you'd like to see added and to what rule set**
it would be nice if there was a `strict` rule set that had all rules enabled by defaulrt

**Additional context**
i prefer to enable all available lint rules then manually disable ones i don't like as i encounter them. currently i have to scroll through [this list](https://dart-lang.github.io/linter/lints/) and manually add the ones that aren't in `core` or `recommended` to my config

**Comment by natebosch** [comment]
I'm not sure if the lints package is the right place to ship this - we'd have to keep it up to date as we add lints.

I think if the goal is to switch to an opt-out approach to linting instead of opt-in it's a feature we should have either baked in to the analysis options, or ship the list with the linter package instead.

What do you think @pq @bwilkerson

**Comment by bwilkerson** [comment]
The linter already has a file that contains all of the lint rules in the form of an analysis options file: https://github.com/dart-lang/linter/blob/master/example/all.yaml. It's intended to be a place from which users can copy new lint names as they're added.

We don't recommend using it as-is because not all lints are appropriate for all users (some even conflict with each other).

But I don't know that we'd considered the use case of including an inclusive list and then disabling the ones you decided you don't want. I suppose we could move the file inside `lib` so that it could be included by users.

There's a pitfall here, though. In order to include this file you'd have to have a dependency on the `linter` package, which in turn has a dependency on the `analyzer` package. Making it a dev dependency would keep the dependency from bloating your application, but it might still cause version solving issues sometimes. I'm not convinced that we want packages to depend on the `linter` package.

**Comment by devoncarew** [comment]
Thanks for the proposal! Closing as I think this is out-of-scope for this package.
