### ISSUE TITLE
Add `cancel_subscriptions` and `close_sinks` to the recommended lint set

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/lints#84]
**Describe the rule you'd like to see added and to what rule set**
`cancel_subscriptions` and `close_sinks` should be added to the recommended lint set.

**Additional context**
Both lints hint the developer at possible memory leaks, which is a very useful hint.
I was a bit surprised that these lints are not part of any lint set (neither core, recommended or flutter_lints have them)

**Comment by natebosch** [comment]
I think these lints have too many false positives to recommend universally.

**Comment by lrhn** [comment]
The lints would need to be more optimistic about when they consider a subscription cancelled.

Any subscription with an `onDone` handler should likely be assumed to always run to completion, and not need a cancel.
Any subscription passed as argument to other code should likely be assumed to be handled by that code (because that's how various "disposer" objects work).

**Comment by devoncarew** [comment]
Thank you for the proposal! From a discussion, we think that the these rules have too many false positives - that they're unlikely to be useful for a general recommendation lint set.
